name: agentproof
region: nyc
services:
  - name: api
    github:
      repo: packtman/Agentproof
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_PATH
        value: /app/data/agentproof.db
      - key: JWT_PRIVATE_KEY
        type: SECRET
      - key: JWT_PUBLIC_KEY
        type: SECRET
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
